### ISSUE TITLE
Installer fails to write logs

### ISSUE THREAD

**Issue by mauriciojost** [mauriciojost/olympus-photosync#17]
After installing .deb package, and executing `photosync` there is no log created and there is an exception thrown: 

```
mjost@tuca:/tmp/glo$ photosync 
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /var/log/photosync/photosync.log (Permission denied)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:142)
	at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
	at org.apache.log4j.RollingFileAppender.setFile(RollingFileAppender.java:207)
	at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:172)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:104)
	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:842)
	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
	at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:648)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:514)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:580)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
	at org.slf4j.impl.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:66)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:270)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:281)
	at org.mauritania.photosync.starter.Starter$.<init>(Starter.scala:12)
	at org.mauritania.photosync.starter.Starter$.<clinit>(Starter.scala)
	at org.mauritania.photosync.starter.Starter.main(Starter.scala)
[15:08:36,121 DEBUG   Starter$] DEBUG
[15:08:36,122 INFO    Starter$] INFO
[15:08:36,122 WARN    Starter$] WARN
[15:08:36,122 ERROR   Starter$] ERROR

```

**Comment by mauriciojost** [comment]
Fixed.
