### ISSUE TITLE
Java error on Mac OS High Sierra

### ISSUE THREAD

**Issue by hercule115** [mauriciojost/olympus-photosync#31]
Hi,

First, let me congratulate for your efforts about photo sync. 
I just install it on my MacBook Air running the **latest High Sierra**.

I started photo sync from the terminal after connected my Mac to the camera with wifi.
From the log output, I can read that Photosync has successfully retrieved the pictures list from the camera. So far so good.

Now when Photosync tries to download the first picture, It gets the following java exception:

...
[09:42:53,010 DEBUG CameraClient] HTML ROOT BEGIN (100OLYMP)
[09:42:53,011 DEBUG CameraClient] <!DOCTYPE html>
[09:42:53,011 DEBUG CameraClient] <html>
[09:42:53,011 DEBUG CameraClient] <head>
[09:42:53,012 DEBUG CameraClient] <META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=shift_jis">
[09:42:53,012 DEBUG CameraClient] <meta name="viewport" content="width=device-width" />
[09:42:53,012 DEBUG CameraClient] <style TYPE="text/css">
[09:42:53,012 DEBUG CameraClient] a{text-decoration:none}
[09:42:53,012 DEBUG CameraClient] img{border-style:none;margin:0}
[09:42:53,013 DEBUG CameraClient] .box{background-position:center;border:thin solid #2E2E2E;box-shadow:3px 3px 3px rgba(0,0,0,0.4); background-color:#000000; color:#929292;float:left;font-size:10px;margin:5px;padding:4px;}
[09:42:53,013 DEBUG CameraClient] 
[09:42:53,013 DEBUG CameraClient] </style>
[09:42:53,013 DEBUG CameraClient] <script type="text/javascript">
[09:42:53,013 DEBUG CameraClient] wlansd = new Array();
[09:42:53,014 DEBUG CameraClient] wlansd[0]="/DCIM/100OLYMP,PB150001.JPG,3192114,0,19311,45705";
[09:42:53,014 DEBUG CameraClient] wlansd[1]="/DCIM/100OLYMP,PB150002.JPG,3084730,0,19311,45961";
[09:42:53,014 DEBUG CameraClient] wlansd[2]="/DCIM/100OLYMP,PB150010.JPG,3135582,0,19311,47687";
[09:42:53,014 DEBUG CameraClient] wlansd[3]="/DCIM/100OLYMP,PB150004.JPG,3641370,0,19311,46296";
[09:42:53,014 DEBUG CameraClient] wlansd[4]="/DCIM/100OLYMP,PB150011.JPG,3236170,0,19311,47769";
[09:42:53,014 DEBUG CameraClient] wlansd[5]="/DCIM/100OLYMP,PB150006.JPG,3249720,0,19311,46384";
[09:42:53,015 DEBUG CameraClient] wlansd[6]="/DCIM/100OLYMP,PB150007.JPG,2886653,0,19311,46407";
[09:42:53,015 DEBUG CameraClient] wlansd[7]="/DCIM/100OLYMP,PB150012.JPG,3208190,0,19311,47780";
[09:42:53,015 DEBUG CameraClient] wlansd[8]="/DCIM/100OLYMP,PB150009.JPG,3074062,0,19311,47168";
[09:42:53,015 DEBUG CameraClient] wlansd[9]="/DCIM/100OLYMP,PB150013.JPG,3420543,0,19311,48458";
[09:42:53,016 DEBUG CameraClient] wlansd[10]="/DCIM/100OLYMP,PB160014.JPG,1389247,0,19312,14";
[09:42:53,016 DEBUG CameraClient] wlansd.sort(cmptime);
[09:42:53,016 DEBUG CameraClient] wlansd.sort(cmpdate);
[09:42:53,016 DEBUG CameraClient] wlansd.reverse();
[09:42:53,016 DEBUG CameraClient] function cmptime(a, b){var g = a.split(",");var f = b.split(",");return g[5] - f[5];}
[09:42:53,016 DEBUG CameraClient] function cmpdate(a, b){var g = a.split(",");var f = b.split(",");return g[4] - f[4];}
[09:42:53,016 DEBUG CameraClient] 
[09:42:53,017 DEBUG CameraClient] icon = new Array();
[09:42:53,017 DEBUG CameraClient] for( i = 0 ; i < wlansd.length ; i ++ ){
[09:42:53,017 DEBUG CameraClient] var b = wlansd[i].split(",");
[09:42:53,017 DEBUG CameraClient] var name = b[1];
[09:42:53,017 DEBUG CameraClient] var ext = name.split(".");
[09:42:53,017 DEBUG CameraClient] if( !(b[3] & 0x10) ){
[09:42:53,017 DEBUG CameraClient] if(( ext[1] == "JPG" )||(ext[1] == "ORF")||(ext[1] == "MPO")||(ext[1] == "MOV")||(ext[1] == "AVI")){icon[i] = "/get_thumbnail.cgi?DIR="+b[0]+"/"+name;}
[09:42:53,018 DEBUG CameraClient] else{icon[i] = "";}
[09:42:53,018 DEBUG CameraClient] }
[09:42:53,018 DEBUG CameraClient] else{
[09:42:53,018 DEBUG CameraClient] icon[i] = "";
[09:42:53,018 DEBUG CameraClient] }
[09:42:53,018 DEBUG CameraClient] }
[09:42:53,019 DEBUG CameraClient] flag = true;
[09:42:53,019 DEBUG CameraClient] cnt = 0;
[09:42:53,019 DEBUG CameraClient] ltmo = 0;
[09:42:53,019 DEBUG CameraClient] io = new Image();
[09:42:53,019 DEBUG CameraClient] function LoadImgs() { 
[09:42:53,019 DEBUG CameraClient] if( flag ){ io.src = icon[cnt]; flag = false;}
[09:42:53,019 DEBUG CameraClient] 
[09:42:53,020 DEBUG CameraClient] if( io.complete ){
[09:42:53,020 DEBUG CameraClient] if( io.width > 30 ){
[09:42:53,020 DEBUG CameraClient] var box = document.images[("n" + cnt)];
[09:42:53,020 DEBUG CameraClient] box.src = icon[cnt];
[09:42:53,020 DEBUG CameraClient] if( (io.width == 120) && (io.height == 160) ){
[09:42:53,020 DEBUG CameraClient] box.width = io.width*(3.0/4.0);
[09:42:53,020 DEBUG CameraClient] box.height = io.height*(3.0/4.0);
[09:42:53,020 DEBUG CameraClient] box.style.marginLeft = "18px";
[09:42:53,021 DEBUG CameraClient] box.style.marginRight = "17px";
[09:42:53,021 DEBUG CameraClient] }
[09:42:53,021 DEBUG CameraClient] }
[09:42:53,021 DEBUG CameraClient] io = new Image();
[09:42:53,021 DEBUG CameraClient] cnt++;
[09:42:53,021 DEBUG CameraClient] if( cnt < icon.length ){io.src = icon[cnt];}
[09:42:53,021 DEBUG CameraClient] ltmo = 0;
[09:42:53,022 DEBUG CameraClient] }
[09:42:53,022 DEBUG CameraClient] else{
[09:42:53,022 DEBUG CameraClient] if(ltmo > 90 ){
[09:42:53,022 DEBUG CameraClient] io = new Image();
[09:42:53,022 DEBUG CameraClient] cnt++;
[09:42:53,022 DEBUG CameraClient] if( cnt < icon.length ){io.src = icon[cnt];}
[09:42:53,022 DEBUG CameraClient] ltmo = 0;
[09:42:53,023 DEBUG CameraClient] }
[09:42:53,023 DEBUG CameraClient] else{
[09:42:53,023 DEBUG CameraClient] ltmo ++;
[09:42:53,023 DEBUG CameraClient] }
[09:42:53,023 DEBUG CameraClient] }
[09:42:53,023 DEBUG CameraClient] if( cnt < icon.length ){
[09:42:53,023 DEBUG CameraClient] setTimeout("LoadImgs()",30);
[09:42:53,023 DEBUG CameraClient] }
[09:42:53,024 DEBUG CameraClient] }
[09:42:53,024 DEBUG CameraClient] 
[09:42:53,024 DEBUG CameraClient] function list(){
[09:42:53,024 DEBUG CameraClient] for( i = 0 ; i < wlansd.length ; i ++ ){
[09:42:53,024 DEBUG CameraClient] var b = wlansd[i].split(",");
[09:42:53,024 DEBUG CameraClient] var path = b[0];
[09:42:53,024 DEBUG CameraClient] var name = b[1];
[09:42:53,025 DEBUG CameraClient] var href = path + "/" + name;
[09:42:53,025 DEBUG CameraClient] var href2 = path + "/FILE.html?" + href;
[09:42:53,025 DEBUG CameraClient] document.write('<div style="background-color: #2E2E2E;" class="box"><a href="'+href2+'"><img width="80" height="60" name="n'+i+'"><br>'+'<font color="#929292">'+name+'</font>'+'</a><br></div>');
[09:42:53,025 DEBUG CameraClient] }
[09:42:53,025 DEBUG CameraClient] }
[09:42:53,025 DEBUG CameraClient] </script>
[09:42:53,025 DEBUG CameraClient] </head>
[09:42:53,025 DEBUG CameraClient] <body background="/WEB_PARTS/bg_1px.gif" onLoad="LoadImgs()" align=center>
[09:42:53,026 DEBUG CameraClient] <center>
[09:42:53,026 DEBUG CameraClient] <img src = "/WEB_PARTS/title.gif" width="300px" height="27px" alt="TITLE">
[09:42:53,026 DEBUG CameraClient] <hr color="#2E2E2E">
[09:42:53,026 DEBUG CameraClient] <div style="position: relative;">
[09:42:53,026 DEBUG CameraClient] <div style="background-color: #2E2E2E; padding: 10px; margin-bottom: 10px; border: 1px solid #2E2E2E;">
[09:42:53,026 DEBUG CameraClient] <div align="left">
[09:42:53,026 DEBUG CameraClient] <font color="#929292">></font><a href="/DCIM"><font color="#929292">DCIM</font></a><font color="#929292">></font>
[09:42:53,027 DEBUG CameraClient] <script type="text/javascript">
[09:42:53,027 DEBUG CameraClient] var path = location.pathname;
[09:42:53,027 DEBUG CameraClient] var dcf = path.split("/");
[09:42:53,027 DEBUG CameraClient] document.write('<font color="#929292">'+dcf[2]+'</font>');
[09:42:53,027 DEBUG CameraClient] </script>
[09:42:53,027 DEBUG CameraClient] </font>
[09:42:53,028 DEBUG CameraClient] <br>
[09:42:53,028 DEBUG CameraClient] </div>
[09:42:53,028 DEBUG CameraClient] </div>
[09:42:53,028 DEBUG CameraClient] </div>
[09:42:53,028 DEBUG CameraClient] <script type="text/javascript">
[09:42:53,028 DEBUG CameraClient] list();
[09:42:53,028 DEBUG CameraClient] </script>
[09:42:53,029 DEBUG CameraClient] </center>
[09:42:53,029 DEBUG CameraClient] </body>
[09:42:53,029 DEBUG CameraClient] </html>
[09:42:53,029 DEBUG CameraClient] HTML ROOT END (100OLYMP)

Exception in thread "main" java.lang.NoClassDefFoundError: java/time/LocalDate
	at org.mauritania.photosync.olympus.sync.FileInfo$.<init>(FileInfo.scala:40)
	at org.mauritania.photosync.olympus.sync.FileInfo$.<clinit>(FileInfo.scala)
	at org.mauritania.photosync.olympus.sync.FileInfo.getHumanDate(FileInfo.scala:21)
	at org.mauritania.photosync.olympus.client.CameraClient$$anonfun$listFiles$3.apply(CameraClient.scala:38)
	at org.mauritania.photosync.olympus.client.CameraClient$$anonfun$listFiles$3.apply(CameraClient.scala:38)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.mauritania.photosync.olympus.client.CameraClient.listFiles(CameraClient.scala:38)
	at org.mauritania.photosync.olympus.sync.FilesManager.listRemoteFiles(FilesManager.scala:38)
	at org.mauritania.photosync.olympus.sync.FilesManager.sync(FilesManager.scala:48)
	at org.mauritania.photosync.starter.Starter$.startSynchronization(Starter.scala:51)
	at org.mauritania.photosync.starter.Starter$.startApp(Starter.scala:34)
	at org.mauritania.photosync.starter.Starter$.main(Starter.scala:17)
	at org.mauritania.photosync.starter.Starter.main(Starter.scala)
Caused by: java.lang.ClassNotFoundException: java.time.LocalDate
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	... 13 more
MyMacBook:bin didier$ 

FYI, The Java version is:

MyMacBook:bin didier$ java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)

Could you help me ?

Many thanks,
Didier

**Comment by mauriciojost** [comment]
Could you please upgrade Java an try again? Use Java 7 or Java 8 at least.

**Comment by hercule115** [comment]
Hi,
I just upgraded to Java 9 and I confirms it works great on High Sierra!
Thanks a lot. Very useful.

Question: Is there any on-going activities for a GUI?
If not, I will start one .

regards
Didier

**Comment by mauriciojost** [comment]
Glad to hear it worked with a newer version of Java. 
Closing this issue. 
With regards to the UI (great @hercule115 !) , I propose you to continue the discussion here: https://github.com/mauriciojost/olympus-photosync/issues/20
