### ISSUE TITLE
"Application failed" using --from and --until options 

### ISSUE THREAD

**Issue by CecileRobin** [mauriciojost/olympus-photosync#75]
Hi,

I am using olympus-photosync on linux (Ubuntu 18.04) using the command line. I have no problem retrieving my pictures using the --output-directory option, but when I specify the "from" and "until" dates, the app crashes with the below message. My camera is Olympus Tough TG-6, and I have set the date on the camera to the same format dd-mm-yyyy (however I did not select the option to include the date stamps on photos themselves

Command:

~$ **olympus-photosync --output-directory ~/2020/camera_macro --from 08-06-2020 --until 16-06-2020**

Output:

```
[17:50:49,865 INFO    Starter$] Version: 1.0.0
[17:50:50,175 INFO    Starter$] Loading file configuration: PhotosyncConfig(CameraClientConfig(http,192.168.0.10,80,/DCIM,wlan.*=.*,(.*),(\d+),(\d+),(\d+),(\d+).*,true,None,None),output,Criteria(None,None,None),false,false,false,false,GuiConfig(true,100))
[17:50:50,176 DEBUG        Os$] Detected OS: Linux (property value 'linux')
Error: Option --from failed when given '08-06-2020'. Text '08-06-2020' could not be parsed at index 0
Error: Option --until failed when given '16-06-2020'. Text '16-06-2020' could not be parsed at index 0
Try --help for more information.
[17:50:50,208 ERROR   Starter$] Application failed
java.lang.IllegalArgumentException: Bad command line arguments!
	at org.mauritania.photosync.starter.Starter$.startApp(Starter.scala:46)
	at org.mauritania.photosync.starter.Starter$.main(Starter.scala:23)
	at org.mauritania.photosync.starter.Starter.main(Starter.scala)
Exception in thread "main" java.lang.IllegalArgumentException: Bad command line arguments!
	at org.mauritania.photosync.starter.Starter$.startApp(Starter.scala:46)
	at org.mauritania.photosync.starter.Starter$.main(Starter.scala:23)
	at org.mauritania.photosync.starter.Starter.main(Starter.scala)
```
Thanks for the app!

**Comment by mauriciojost** [comment]
Thanks for taking the time to file the issue! Try the format YYYY-MM-DD instead. Its a documentation problem probably.

**Comment by mauriciojost** [comment]
Documentation fixed.

**Comment by mauriciojost** [comment]
Please re-open if not the case.

**Comment by CecileRobin** [comment]
worked thanks!
